
tasks:
  - before: echo 'before tasks go here'
    init: | # runs during prebuild
        go install
        go build 
    command: ./foxhole-go-gitpod-demo

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - golang.go